---
- hosts: all 
  tasks:
    - name: Start master container
      docker_container:
        name: "{{ conjur_leader_name }}"
        image: "{{ conjur_image_name }}"
        state: started
        restart_policy: unless-stopped
        security_opts:
          - seccomp:unconfined
        pull: yes
        exposed_ports:
          - '443'
          - '444'
          - '1999'
          - '5432'
        published_ports:
          - "443:443"
          - "444:444"
          - "1999:1999"
          - "5432:5432"
        log_driver: journald
        volumes:
          - "/opt/cyberark/dap/configuration:/opt/cyberark/dap/configuration:rw"
          - "/opt/cyberark/dap/security:/opt/cyberark/dap/security:rw"
          - "/opt/cyberark/dap/backups:/opt/conjur/backup:rw"
          - "/opt/cyberark/dap/seeds:/opt/cyberark/dap/seeds:rw"
          - "/opt/cyberark/dap/logs:/var/log/conjur:rw"
          
    - name: Configure Dap master
      shell: |
        "docker exec {{ conjur_leader_name }} evoke configure master --accept-eula --hostname {{ conjur_leader_name }} --admin-password {{ conjur_admin_password }} {{ conjur_company }}"
      args:
        executable: /bin/bash

  vars:
    - conjur_image_name: 'captainfluffytoes/dap:latest'
    - conjur_leader_name: 'conjurleader'
    - conjur_admin_password: 'CyberArk123!'
    - conjur_company: 'cyberark'
    - ansible_python_interpreter: /usr/bin/python3